### PR TITLE
feat: adding resource and label support

### PR DESCRIPTION
**Pull request by abcdlsj**
Add Google Keep tags and images to upload to Memos.

### CODE REVIEW

**Comment by MatthieuTinnes** [comment]
Hello, thanks for your PR, I will review and test it soon

**Comment by MatthieuTinnes** [comment]
Resources are added to the server, but not linked correctly with memos.

**Comment by MatthieuTinnes** [comment]
I've added a call to "SetMemoResources", the memos frontend use this endpoint to add an attachement to memos.

**Comment by MatthieuTinnes** [comment]
@all-contributors please add @jakebolam for code

**Comment by MatthieuTinnes** [comment]
@all-contributors please add @abcdlsj for code

**Comment by abcdlsj** [comment]
@MatthieuTinnes thanks for reviewing and testing these changes!

I just reviewed the Memos code and API document and found that the latest version can the ability to associate resources with creating memos, so I tested pass.

but I really shouldn't be using the rc version for development, thanks again for the your reviewing!

Code: https://github.com/usememos/memos/blob/fcc4abf5b8be6269410421dec5d0fd31a8d53338/server/router/api/v1/memo_service.go#L78

**Pull request merged**
